services:
  admin-postgres:
    image: postgres

    container_name: admin-panel-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: admin_db

    ports:
      - "5434:5432"

    volumes:
      - ./admin_db/init-scripts:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4

    container_name: admin-pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "8888:80"

    depends_on:
      - admin-postgres
